exec = hello.out
sources = $(wildcards src/*.c)
objects = $(sources:.c=.o)
flags = -g

$exec = $(objects)
		gcc $(objects) $(flags) -o $(exec)

%.o: %c include/%.h
	gcc -c $(flags) $< -o $@

clean:
	-rm *.out
	-rm *.o
	-rm src/*.o